spring:
  profiles:
    include: secrets
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  queries:
    users-query: select email, password, 1 from user where email=?
    roles-query: select email, role from user where email=?
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true 
  mvc:
      throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
